
package com.accenture.fe.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductStockWebServiceImplService", targetNamespace = "http://ws.fe.accenture.com/", wsdlLocation = "http://localhost:8080/ws/ProductStockWebService?wsdl")
public class ProductStockWebServiceImplService
    extends Service
{

    private final static URL PRODUCTSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRODUCTSTOCKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.fe.accenture.com/", "ProductStockWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/ProductStockWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRODUCTSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProductStockWebServiceImplService() {
        super(__getWsdlLocation(), PRODUCTSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ProductStockWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductStockWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ProductStockWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductStockWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductStockWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductStockWebService
     */
    @WebEndpoint(name = "ProductStockWebServiceImplPort")
    public ProductStockWebService getProductStockWebServiceImplPort() {
        return super.getPort(new QName("http://ws.fe.accenture.com/", "ProductStockWebServiceImplPort"), ProductStockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductStockWebService
     */
    @WebEndpoint(name = "ProductStockWebServiceImplPort")
    public ProductStockWebService getProductStockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fe.accenture.com/", "ProductStockWebServiceImplPort"), ProductStockWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRODUCTSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRODUCTSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
